apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pagamento-application
  labels:
    app: deployment-pagamento-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-pagamento-application
  template:
    metadata:
      labels:
        app: deployment-pagamento-application
    spec:
      containers:
        - name: deployment-pagamento-application
          image: {{ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{ECR_REPOSITORY}}:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secret-mongo-db
                  key: mongo_uri
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-mongo-db
                  key: mongo_db_name
          readinessProbe:
            httpGet:
              path: /lanchonete/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /lanchonete/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            requests:
              cpu: 700m
              memory: 600Mi
            limits:
              cpu: 1400m
              memory: 2Gi